### ISSUE TITLE
after installing vagrant-1.7.4 can't start

### ISSUE THREAD

**Issue by oz123** [deogracia/deogracia-vagrant-gentoo-overlay#10]
This is the error I see:

```
[18] ozn@yeni2gen:~ $ vagrant
/usr/lib64/ruby/gems/2.0.0/gems/vagrant-1.7.4/lib/vagrant.rb:59:in `require': cannot load such file -- i18n (LoadError)
    from /usr/lib64/ruby/gems/2.0.0/gems/vagrant-1.7.4/lib/vagrant.rb:59:in `<top (required)>'
    from /usr/lib64/ruby/gems/2.0.0/gems/vagrant-1.7.4/bin/vagrant:109:in `require'
    from /usr/lib64/ruby/gems/2.0.0/gems/vagrant-1.7.4/bin/vagrant:109:in `<top (required)>'
    from /usr/bin/vagrant:9:in `load'
    from /usr/bin/vagrant:9:in `<main>'
[19] ozn@yeni2gen:~ $ vagrant -v
Vagrant 1.7.4
```

**Comment by deogracia** [comment]
hi, 
I'll try from scratch asap.

**Comment by deogracia** [comment]
I'm so sorry @oz123 . I totally forgot your issue. More, in the meantime, I stopped use gentoo.

I'll keep this issue open till I hear from you back. But I'm not sure I'll be able to help you.

**Comment by oz123** [comment]
@deogracia Thanks for the message. Sorry to hear you stopped using Gentoo. In the meanwhile Gentoo's own vagrant is updated.

**Comment by deogracia** [comment]
Thanks for the news ^^

++
